name: Check Proposal Status

on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-proposals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable

      - name: Check Proposals
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn sync:proposals

      - name: Commit and Push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/proposal_status.md
          if ! git diff --cached --exit-code; then
            git commit -m "docs: update proposal status [skip ci]"
            git push
          fi
